version: 2

updates:
  # Maintain dependencies for Github Actions
  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      interval: weekly
      day: friday
    commit-message:
      prefix: deps
    labels:
      - dependencies
    assignees:
      - benyap

  # Maintain dependencies for npm
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: friday
    commit-message:
      prefix: deps
    labels:
      - dependencies
    assignees:
      - benyap
